Update assemble

diff --git a/tomcat-sti/.s2i/bin/assemble b/tomcat-sti/.s2i/bin/assemble
--- a/tomcat-sti/.s2i/bin/assemble
+++ b/tomcat-sti/.s2i/bin/assemble
@@ -132,9 +132,9 @@ fi
 
 # As SpringBoot you should only have 1 fat jar
 if [ $(ls /opt/openshift/*.jar | wc -l) -eq 1 ]; then
-  mv /opt/openshift/*.jar /opt/openshift/app.jar
-  [ ! -f /opt/openshift/app.jar ] && echo "Application could not be properly built." && exit 1 
-  echo "Application jar file is located in /opt/openshift/app.jar"
+  mv /opt/openshift/*.war /usr/local/tomcat/webapp/
+  ##[ ! -f /opt/openshift/app.jar ] && echo "Application could not be properly built." && exit 1 
+  echo "Application jar file is located is  copied /usr/local/tomcat/webapp"
 else
   exit 1
 fi
